version: '3.8'

services:
  app:
    image: harbor.chinahuanong.com.cn/release/ai-codereview-gitlab:1.0-amd64
    container_name: ai-codereview-gitlab-app
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./conf/.env:/app/conf/.env
      - ./log:/app/log
      - ./data:/app/data
    restart: unless-stopped